### ISSUE TITLE
Complete the data upload for new data pre-2024 hackweek

### ISSUE THREAD

**Issue by micah-prime** [SnowEx/snowex_db#24]
Checklist of new data uploads pre-hackeweek 2024, finishing issues #22 #20 #18 

- [x] Clear all pit data
- [x] Upload previous pit data
- [x] Upload met station data from GM (#20)
- [x] Upload 2020 and 2021 timeseries pits #18 
- [x] Upload 2020 and 2021 SWE summary files #18 
- [x] Upload Alaska 2023 pit data #22 
- [x] Upload Alaska 2023 SWE summary files #22

**Comment by micah-prime** [comment]
Status update - snowexsql 0.4.1 and current snowex_db version are on the server

**Comment by micah-prime** [comment]
- Preliminary 23 data uploaded to the server
- Timeseries pits 2020 v2 and 2021 v1 downloaded onto the server

**Comment by micah-prime** [comment]
- Ran script to remove pits
- Ran script to upload IOP pits

**Comment by micah-prime** [comment]
* Ran script to upload SSA
 * This puts us up to 53781 entries, roughly 448 pits

**Comment by micah-prime** [comment]
* Ran script to upload 2020, 2021, and Alaska SWE summary files

**Comment by micah-prime** [comment]
Upgraded snowex_db and uploaded station data
